Update maven-publish.yml

diff --git a/.github/workflows/maven-publish.yml b/.github/workflows/maven-publish.yml
--- a/.github/workflows/maven-publish.yml
+++ b/.github/workflows/maven-publish.yml
@@ -26,7 +26,12 @@ jobs:
         distribution: 'temurin'
         server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
         settings-path: ${{ github.workspace }} # location for the settings.xml file
-
+    - name: Check for pom.xml existence
+      run: |
+        if [ ! -f "pom.xml" ]; then
+          echo "Error: pom.xml not found. Please build or generate the project before running Maven commands."
+          exit 1
+        fi
     - name: Build with Maven
       run: mvn -B package --file pom.xml
 
